
export interface ServiceConfigItem {
  env_sistema: string;
  env_servico: string;
  default_sistema?: string;
  default_servico?: string;
  versaoSistema?: string;
  tipo: 'Consultar' | 'Emitir' | 'Solicitar' | 'Apoiar';
  descricao?: string;
  uso?: string;
  finalidade?: string;
  status?: 'ativo' | 'nao_assinada';
}

// Espelho do catálogo do bot-backend (bot-backend/src/lib/serpro-config.ts).
// Usado apenas para UI (dropdown, badges, metadados). As chamadas reais sempre passam pelo backend.
// IMPORTANTE: manter sincronizado com o backend — serviços removidos de lá devem ser removidos aqui.
export const SERVICE_CONFIG: Record<string, ServiceConfigItem> = {
  CCMEI_DADOS: {
    env_sistema: 'INTEGRA_CCMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_CCMEI_DADOS_ID_SERVICO',
    default_sistema: 'CCMEI',
    default_servico: 'DADOSCCMEI122',
    tipo: 'Consultar',
    descricao: 'Consulta dados cadastrais completos do MEI.',
    uso: 'Requer apenas CNPJ.',
    finalidade: 'Verificar situação cadastral, atividades e endereço.',
    status: 'ativo',
  },
  PGMEI: {
    env_sistema: 'INTEGRA_PGMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_PGMEI_ID_SERVICO',
    default_sistema: 'PGMEI',
    default_servico: 'DIVIDAATIVA24',
    versaoSistema: '2.4',
    tipo: 'Consultar',
    descricao: 'Consulta dívida ativa e débitos via PGMEI.',
    uso: 'Requer CNPJ e Ano (opcional).',
    finalidade: 'Verificar débitos pendentes e inscritos em Dívida Ativa.',
    status: 'ativo',
  },
  PGMEI_EXTRATO: {
    env_sistema: 'INTEGRA_PGMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_PGMEI_GERARDASPDF_ID_SERVICO',
    default_sistema: 'PGMEI',
    default_servico: 'GERARDASPDF21',
    tipo: 'Emitir',
    descricao: 'Geração de PDF do DAS (Extrato/Boleto).',
    uso: 'Requer CNPJ e Período (MM/AAAA).',
    status: 'ativo',
  },
  PGMEI_BOLETO: {
    env_sistema: 'INTEGRA_PGMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_PGMEI_GERARDASCODBARRA_ID_SERVICO',
    default_sistema: 'PGMEI',
    default_servico: 'GERARDASCODBARRA22',
    tipo: 'Emitir',
    descricao: 'Geração de Linha Digitável/Código de Barras do DAS.',
    uso: 'Requer CNPJ e Período (MM/AAAA).',
    status: 'ativo',
  },
  PGMEI_ATU_BENEFICIO: {
    env_sistema: 'INTEGRA_PGMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_PGMEI_ATUBENEFICIO_ID_SERVICO',
    default_sistema: 'PGMEI',
    default_servico: 'ATUBENEFICIO23',
    tipo: 'Emitir',
    descricao: 'Atualização de Benefícios Previdenciários no PGMEI.',
    uso: 'Requer CNPJ.',
    status: 'ativo',
  },
  SIMEI: {
    env_sistema: 'INTEGRA_SIMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_SIMEI_ID_SERVICO',
    default_sistema: 'CCMEI',
    default_servico: 'DADOSCCMEI122',
    tipo: 'Consultar',
    descricao: 'Consulta situação do SIMEI via CCMEI.',
    uso: 'Requer CNPJ e Ano.',
    finalidade: 'Verificar se a empresa é optante pelo SIMEI.',
    status: 'ativo',
  },
  SIT_FISCAL_SOLICITAR: {
    env_sistema: 'INTEGRA_SITFIS_ID_SISTEMA',
    env_servico: 'INTEGRA_SITFIS_PROTOCOLO_ID_SERVICO',
    default_sistema: 'SITFIS',
    default_servico: 'SOLICITARPROTOCOLO91',
    versaoSistema: '2.0',
    tipo: 'Apoiar',
    descricao: 'Solicitação de Protocolo de Situação Fiscal.',
    uso: 'Requer CNPJ.',
    finalidade: 'Primeiro passo para o diagnóstico completo de pendências.',
    status: 'ativo',
  },
  SIT_FISCAL_RELATORIO: {
    env_sistema: 'INTEGRA_SITFIS_ID_SISTEMA',
    env_servico: 'INTEGRA_SITFIS_RELATORIO_ID_SERVICO',
    default_sistema: 'SITFIS',
    default_servico: 'RELATORIOSITFIS92',
    versaoSistema: '2.0',
    tipo: 'Emitir',
    descricao: 'Relatório de Situação Fiscal Completa.',
    uso: 'Requer número do protocolo obtido na solicitação.',
    finalidade: 'Obtenção do relatório detalhado em PDF/JSON.',
    status: 'ativo',
  },
  DASN_SIMEI: {
    env_sistema: 'INTEGRA_DASNSIMEI_ID_SISTEMA',
    env_servico: 'INTEGRA_DASNSIMEI_ID_SERVICO',
    default_sistema: 'DASNSIMEI',
    default_servico: 'CONSULTIMADECREC152',
    tipo: 'Consultar',
    descricao: 'Consulta Declaração Anual do MEI (DASN).',
    uso: 'Requer CNPJ e Ano.',
    finalidade: 'Consultar recibos e situação de declarações anuais (faturamento) entregues pelo MEI.',
    status: 'nao_assinada',
  },
  PGDASD: {
    env_sistema: 'INTEGRA_PGDASD_ID_SISTEMA',
    env_servico: 'INTEGRA_PGDASD_ID_SERVICO',
    default_sistema: 'PGDASD',
    default_servico: 'CONSEXTRATO16',
    tipo: 'Consultar',
    descricao: 'Extrato PGDAS-D (Simples Nacional).',
    uso: 'Requer CNPJ e Ano Calendário.',
    finalidade: 'Consultar declarações transmitidas e situação do PGDAS-D.',
    status: 'ativo',
  },
  DCTFWEB: {
    env_sistema: 'INTEGRA_DCTFWEB_ID_SISTEMA',
    env_servico: 'INTEGRA_DCTFWEB_ID_SERVICO',
    default_sistema: 'DCTFWEB',
    default_servico: 'CONSDECCOMPLETA33',
    tipo: 'Consultar',
    descricao: 'Consulta Declaração DCTFWeb Completa.',
    uso: 'Requer CNPJ e Período (MM/AAAA).',
    finalidade: 'Consultar débitos e créditos tributários previdenciários.',
    status: 'ativo',
  },
  PARCELAMENTO_MEI_CONSULTAR: {
    env_sistema: 'INTEGRA_PARCMEI_SISTEMA',
    env_servico: 'INTEGRA_PARCMEI_CONSULTAR_SERVICO',
    default_sistema: 'PARCMEI',
    default_servico: 'PEDIDOSPARC203',
    tipo: 'Consultar',
    descricao: 'Consulta Pedidos de Parcelamento MEI.',
    finalidade: 'Verificar status e parcelas de acordos ativos.',
    status: 'ativo',
  },
  PARCELAMENTO_MEI_EMITIR: {
    env_sistema: 'INTEGRA_PARCMEI_SISTEMA',
    env_servico: 'INTEGRA_PARCMEI_GERAR_SERVICO',
    default_sistema: 'PARCMEI',
    default_servico: 'GERARDAS201',
    tipo: 'Emitir',
    descricao: 'Emissão de DAS de Parcelamento MEI.',
    status: 'ativo',
  },
  PARCELAMENTO_SN_CONSULTAR: {
    env_sistema: 'INTEGRA_PARCSN_SISTEMA',
    env_servico: 'INTEGRA_PARCSN_CONSULTAR_SERVICO',
    default_sistema: 'PARCSN',
    default_servico: 'PEDIDOSPARC163',
    tipo: 'Consultar',
    descricao: 'Consulta de Pedidos de Parcelamento Simples Nacional.',
    status: 'ativo',
  },
  PARCELAMENTO_SN_EMITIR: {
    env_sistema: 'INTEGRA_PARCSN_SISTEMA',
    env_servico: 'INTEGRA_PARCSN_GERAR_SERVICO',
    default_sistema: 'PARCSN',
    default_servico: 'GERARDAS161',
    tipo: 'Emitir',
    descricao: 'Emissão de DAS de Parcelamento Simples Nacional.',
    finalidade: 'Gerar guia de pagamento de parcela SN.',
    status: 'ativo',
  },
  PGFN_API: {
    env_sistema: 'PGFN_CLIENT_ID',
    env_servico: 'PGFN_CLIENT_SECRET',
    default_sistema: 'consulta-divida-ativa-df',
    default_servico: 'devedor',
    tipo: 'Consultar',
    descricao: 'Consulta Dívida Ativa PGFN por API avulsa.',
    uso: 'Requer CNPJ. Usa token próprio da API Consulta Dívida Ativa.',
    finalidade: 'Verificar inscrições, valores consolidados e situação na Dívida Ativa da União.',
    status: 'ativo',
  },
  CND: {
    env_sistema: 'INTEGRA_CND_ID_SISTEMA',
    env_servico: 'INTEGRA_CND_ID_SERVICO',
    default_sistema: 'SITFIS',
    default_servico: 'RELATORIOSITFIS92',
    versaoSistema: '2.0',
    tipo: 'Emitir',
    descricao: 'Emissão de Certidão via Relatório de Situação Fiscal.',
    finalidade: 'Comprovar regularidade fiscal perante a Receita Federal.',
    status: 'ativo',
  },
  PROCESSOS: {
    env_sistema: 'INTEGRA_PROCESSOS_ID_SISTEMA',
    env_servico: 'INTEGRA_PROCESSOS_ID_SERVICO',
    default_sistema: 'EPROCESSO',
    default_servico: 'CONSPROCPORINTER271',
    versaoSistema: '2.0',
    tipo: 'Consultar',
    descricao: 'Consulta de Processos Administrativos.',
    status: 'ativo',
  },
  CAIXA_POSTAL: {
    env_sistema: 'INTEGRA_CAIXA_POSTAL_ID_SISTEMA',
    env_servico: 'INTEGRA_CAIXA_POSTAL_ID_SERVICO',
    default_sistema: 'CAIXAPOSTAL',
    default_servico: 'MSGCONTRIBUINTE61',
    tipo: 'Consultar',
    descricao: 'Caixa Postal Eletrônica (DTE).',
    finalidade: 'Ler mensagens e intimações oficiais.',
    status: 'ativo',
  },
  PAGAMENTO: {
    env_sistema: 'INTEGRA_PAGAMENTO_ID_SISTEMA',
    env_servico: 'INTEGRA_PAGAMENTO_ID_SERVICO',
    default_sistema: 'PAGTOWEB',
    default_servico: 'COMPARRECADACAO72',
    tipo: 'Emitir',
    descricao: 'Emissão de Comprovante de Arrecadação.',
    finalidade: 'Verificar pagamentos realizados pelo contribuinte.',
    status: 'ativo',
  },
  PROCURACAO: {
    env_sistema: 'INTEGRA_PROCURACAO_ID_SISTEMA',
    env_servico: 'INTEGRA_PROCURACAO_ID_SERVICO',
    default_sistema: 'PROCURACOES',
    default_servico: 'OBTERPROCURACAO41',
    versaoSistema: '1',
    tipo: 'Consultar',
    descricao: 'Consulta de Procurações Eletrônicas.',
    finalidade: 'Verificar poderes do contador no e-CAC.',
    status: 'ativo',
  },
};
