import { NextResponse } from "next/server";
import pool from "@/lib/db";

async function ensureServicesTable() {
  const client = await pool.connect();
  try {
    const existsRes = await client.query(`
      SELECT EXISTS (
        SELECT 1 
        FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'services'
      ) AS exists
    `);
    const exists = !!existsRes.rows[0]?.exists;

    if (!exists) {
      await client.query(`
        CREATE TABLE services (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          value NUMERIC(10,2) NOT NULL,
          description TEXT,
          created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
          updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
        )
      `);
      return;
    }

    await client.query(
      `ALTER TABLE services ADD COLUMN IF NOT EXISTS name TEXT`,
    );
    await client.query(
      `ALTER TABLE services ADD COLUMN IF NOT EXISTS value NUMERIC(10,2)`,
    );
    await client.query(
      `ALTER TABLE services ADD COLUMN IF NOT EXISTS description TEXT`,
    );
    await client.query(
      `ALTER TABLE services ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE`,
    );
    await client.query(
      `ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE`,
    );
    await client.query(
      `ALTER TABLE services ALTER COLUMN created_at SET DEFAULT NOW()`,
    );
    await client.query(
      `ALTER TABLE services ALTER COLUMN updated_at SET DEFAULT NOW()`,
    );

    const idInfoRes = await client.query(`
      SELECT data_type, is_identity, column_default
      FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'services' AND column_name = 'id'
    `);
    const dataType: string | undefined = idInfoRes.rows[0]?.data_type;
    const isIdentity: string | undefined = idInfoRes.rows[0]?.is_identity;
    const columnDefault: string | null | undefined =
      idInfoRes.rows[0]?.column_default;

    if (dataType === "uuid") {
      if (!columnDefault) {
        await client.query("CREATE EXTENSION IF NOT EXISTS pgcrypto");
        await client.query(
          `ALTER TABLE services ALTER COLUMN id SET DEFAULT gen_random_uuid()`,
        );
      }
    } else if (dataType === "integer") {
      if (isIdentity !== "YES" && !columnDefault) {
        await client.query(
          `ALTER TABLE services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`,
        );
      }
    }
  } finally {
    client.release();
  }
}

async function getServiceColumns() {
  const client = await pool.connect();
  try {
    const res = await client.query(`
      SELECT column_name 
      FROM information_schema.columns 
      WHERE table_schema = 'public' AND table_name = 'services'
    `);
    const cols = res.rows.map((r) => String(r.column_name));
    const nameCol = cols.includes("nome")
      ? "nome"
      : cols.includes("name")
        ? "name"
        : "name";
    const valueCol = cols.includes("valor")
      ? "valor"
      : cols.includes("value")
        ? "value"
        : "value";
    const descriptionCol = cols.includes("descricao")
      ? "descricao"
      : cols.includes("description")
        ? "description"
        : "description";
    return { nameCol, valueCol, descriptionCol };
  } finally {
    client.release();
  }
}

export async function PUT(
  req: Request,
  { params }: { params: { id: string } },
) {
  try {
    await ensureServicesTable();
    const { nameCol, valueCol, descriptionCol } = await getServiceColumns();
    const id = params.id;
    const body = await req.json();
    const name: string | undefined = body?.name;
    const description: string | undefined = body?.description;
    const valueRaw = body?.value;
    const setParts: string[] = [];
    const values: unknown[] = [];
    let idx = 1;
    if (typeof name === "string" && name.length > 0) {
      setParts.push(`${nameCol} = $${idx++}`);
      values.push(name);
    }
    if (valueRaw !== undefined && !Number.isNaN(Number(valueRaw))) {
      setParts.push(`${valueCol} = $${idx++}`);
      values.push(Number(valueRaw));
    }
    if (typeof description === "string") {
      setParts.push(`${descriptionCol} = $${idx++}`);
      values.push(description);
    }
    setParts.push(`updated_at = NOW()`);
    const sql = `UPDATE services SET ${setParts.join(", ")} WHERE id = $${idx} RETURNING id, ${nameCol} AS name, ${valueCol} AS value, ${descriptionCol} AS description, created_at, updated_at`;
    values.push(id);
    const res = await pool.query(sql, values);
    if (res.rowCount === 0) {
      return NextResponse.json(
        { error: "Serviço não encontrado" },
        { status: 404 },
      );
    }
    return NextResponse.json(res.rows[0]);
  } catch {
    return NextResponse.json(
      { error: "Erro ao atualizar serviço" },
      { status: 500 },
    );
  }
}

export async function DELETE(
  _: Request,
  { params }: { params: { id: string } },
) {
  try {
    await ensureServicesTable();
    const id = params.id;
    const res = await pool.query("DELETE FROM services WHERE id = $1", [id]);
    if (res.rowCount === 0) {
      return NextResponse.json(
        { error: "Serviço não encontrado" },
        { status: 404 },
      );
    }
    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json(
      { error: "Erro ao excluir serviço" },
      { status: 500 },
    );
  }
}
